# Site Settings

title: Portfol-X
username: Youstina Kallini
email: yostina_magd91@hotmail.com
description: >-
  This site is under construction.
baseurl: "/"
twitter_username: jekyllrb
github_username:  jekyll


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

